### ISSUE TITLE
Exception when displaying raids

### ISSUE THREAD

**Issue by frdulzuro** [LegoFigure11/RaidCrawler#2]
When reading the raid block I get an exception: 

```
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at RaidCrawler.MainWindow.DisplayRaid(Int32 index) in C:\Users\Lego\Documents\GitHub\RaidCrawler\MainWindow.cs:line 109
   at RaidCrawler.MainWindow.ReadRaids(CancellationToken token) in C:\Users\Lego\Documents\GitHub\RaidCrawler\MainWindow.cs:line 318
   at RaidCrawler.MainWindow.Connect() in C:\Users\Lego\Documents\GitHub\RaidCrawler\MainWindow.cs:line 70
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)

```
After pulling the repo and testing real quick in visual studio code this line:

https://github.com/LegoFigure11/RaidCrawler/blob/7cf42fda5a34a94f2cfd3b90283ae8451d11d714/MainWindow.cs#L288

The Data variable seem to stay unchanged and then the resulting raid created has an Area value too big.
The exception then occurs when displaying the raid.
I double checked and my sysbot seems to be working with your overworld rng program for sword and shield.

If it helps I'm running latest system update/atmosphere/and update for scarlet

**Comment by LegoFigure11** [comment]
Had a few other reports of this, someone on discord found that removing all cheats and Edizon from their switch and then restarting it fixed the issue. I've added a few checks for bad reads in [d6f53d8](https://github.com/LegoFigure11/RaidCrawler/commit/d6f53d80cde4b4c5b63c0b3e073bcb4d765070a8), hopefully this helps. I take it by the fact that you've closed this that you found a solution?
